# Generated by Django 5.2.8 on 2025-12-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
